###
### default application configuration
###

# ================================================================================
# Spring
# ================================================================================
spring:

  # ------------------------------------------------------------------------------
  # main
  # ------------------------------------------------------------------------------
  main:
    showBanner: false

  # ------------------------------------------------------------------------------
  # Groovy template
  #
  # gprdb don't use groovy template, however, template directory check is performed
  # when groovy is found on classpath. threfore, disable the check explicitly.
  # ------------------------------------------------------------------------------
  groovy:
    template:
      checkTemplateLocation: false


# ================================================================================
# server 
# ================================================================================
server:
  port: 8080


# ================================================================================
# management (Spring actuator)
# ================================================================================
management:
  port: 8081
  contextPath: /management


# ================================================================================
# logging
# ================================================================================
logging:
  level:
    io:  ERROR
    jp:  ERROR
    org: ERROR


# ================================================================================
# gprdb configuration
# ================================================================================
gprdb:

  # ------------------------------------------------------------------------------
  # build information 
  # ------------------------------------------------------------------------------
  build:
    version: "${version}"
    commit: "${commit}"
    date: "${date}"
